# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: |
      'Dachun Sun is a Ph.D. candidate in Computer Science at the University of Illinois Urbana-Champaign, specializing in AI and social network analysis. Dachun Sun's research focuses on using machine learning and large language models to understand community behavior, with applications in crisis management and misinformation mitigation. Dachun Sun is also passionate about hands-on, technology-enhanced teaching, with a commitment to fostering continuous learning in computer science education.'
    twitter: 'D_Sun9'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Dachun Sun"

# Site footer
footer:
  copyright:
    notice: '© {year} Dachun Sun. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false

extensions:
  decap_cms:
    branch: main
    # publish_mode: editorial_workflow
    local_backend: true